language: java
sudo: false
script: mvn clean verify
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
   example@gmail.com
   example2@gmail.com
    on_failure: always